root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "templ generate && /usr/tailwindcss -i ./web/input.css -o ./web/static/styles.css  && go build -o ./tmp/main ./main.go"
delay = 0
include_ext = ["go", "templ"]
exclude_unchanged = false
exclude_regex = [".*_templ.go"]
follow_symlink = false
full_bin = ""
include_dir = []
include_file = [".env"]
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
