services:
  app:
    build:
      context: .
    volumes:
      - ./:/usr/src/app:cached
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - 13131:13131
